### PR TITLE
Fix formatting of Schemas

### PR DESCRIPTION
**Pull request by tuckerzp**
https://github.com/usnistgov/OSCAL/compare/main...EasyDynamics:EGRC-402

This makes the diff between our JSON schemas and NIST's less extreme.

### CODE REVIEW

**Comment by tuckerzp** [comment]
This is the script I used! https://gist.github.com/tuckerzp/1d27fa2fae81a56cdd2323667abff480

**Review by rgauss — APPROVED** [review]
Good work!

**Review by laurelmay — APPROVED** [review]

**Comment by tuckerzp** [comment]
Is this good to merge now?

**Comment by laurelmay** [comment]
It sure is! Thank you!

**Pull request merged**
